# Generated by Django 5.0.1 on 2024-01-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('business_name', models.CharField(max_length=255)),
                ('business_gstin', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'ONLINE')], max_length=10)),
                ('payment_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Done', 'Done')], max_length=20)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.consumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
        migrations.AddField(
            model_name='dealer',
            name='product_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='product_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory'),
        ),
    ]
