# Generated by Django 4.2.9 on 2024-01-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
